// Nombres de canales IPC compartidos entre main y preload.
export const IPC = {
  detect: 'teuton:detect',
  getTeutonPath: 'settings:getTeutonPath',
  setTeutonPath: 'settings:setTeutonPath',
  pickDirectory: 'dialog:pickDirectory',
  createProject: 'project:create',
  openProject: 'project:open',
  saveProject: 'project:save',
  check: 'project:check',
  runStart: 'run:start',
  runCancel: 'run:cancel',
  runEvent: 'run:event',
  loadResults: 'results:load',
  exportAs: 'export:as',
  saveFileDialog: 'dialog:saveFile',
  recentProjects: 'project:recents',
  removeRecent: 'project:removeRecent',
  openPath: 'shell:openPath',
  openExternal: 'shell:openExternal',
  getGrading: 'settings:getGrading',
  setGrading: 'settings:setGrading',
  getDefaultGlobals: 'settings:getDefaultGlobals',
  setDefaultGlobals: 'settings:setDefaultGlobals',
  listClasses: 'classes:list',
  saveClass: 'classes:save',
  deleteClass: 'classes:delete',
  getRecords: 'records:get',
  updateRecords: 'records:update',
  resetRecords: 'records:reset',
  getProjectMeta: 'meta:get',
  setProjectMeta: 'meta:set',
  writeClassCsv: 'export:classCsv'
} as const
