#!/usr/bin/env bash
# Preflight review checks for Teutón GUI (Electron + React + TS wrapping the `teuton` CLI).
# Generated by a-review-optimizer on 2026-07-30 (from-scratch build, no prior review skill).
# Runs deterministic pattern checks, outputs JSON for agent consumption.
#
# Deliberately uses only grep/find/awk/python3 (POSIX-ish, real binaries) -- NOT `rg`.
# In this harness `rg`/`grep` are shell functions that proxy through the Claude Code
# binary in an interactive shell, but that function is not inherited by a script
# invoked as `bash file.sh`: there `rg` resolves to nothing, and `grep` resolves to the
# real /usr/bin/grep. A preflight script must work when *run*, not just when typed at
# an interactive prompt, so it has to stick to what's actually on PATH in that context.
#
# Usage: bash .claude/scripts/teuton-preflight.sh [SRC_DIR]
#   SRC_DIR defaults to src/ (repo root when run from project root).

set -euo pipefail

SRC_DIR="${1:-src}"
cd "$(dirname "$0")/../.." # repo root, so SRC_DIR/package.json paths resolve regardless of cwd

RESULTS_FILE=$(mktemp)
echo '{' > "$RESULTS_FILE"
FIRST=true

emit() {
    local id="$1" name="$2" agent="$3" status="$4" count="$5"
    shift 5
    local locations="[]"
    if [ $# -gt 0 ]; then
        locations=$(printf '%s\n' "$@" | python3 -c "
import sys, json
print(json.dumps([l.strip() for l in sys.stdin if l.strip()]))")
    fi
    if [ "$FIRST" = true ]; then FIRST=false; else echo ',' >> "$RESULTS_FILE"; fi
    cat >> "$RESULTS_FILE" <<ITEM
  "$id": {
    "name": "$name",
    "agent": "$agent",
    "status": "$status",
    "count": $count,
    "locations": $locations
  }
ITEM
}

count_of() { echo "$1" | grep -c . 2>/dev/null || true; }

# ============================================================
# GROUP SEC: Security & Trust-Boundary Checks -> Security agent
# ============================================================

# SEC-01: subprocess/spawn/execFile with shell:true (this project's convention is
# args-array, never a shell string -- contextIsolation + no-shell is load-bearing).
HITS=$(grep -rnE --include='*.ts' 'shell[[:space:]]*:[[:space:]]*true' "$SRC_DIR" 2>/dev/null || true)
COUNT=$(count_of "$HITS")
if [ "$COUNT" -gt 0 ]; then
    LOCS=$(echo "$HITS" | awk -F: '{print $1":"$2}')
    emit "SEC-01" "spawn/execFile with shell:true" "security" "fail" "$COUNT" $LOCS
else
    emit "SEC-01" "spawn/execFile with shell:true" "security" "pass" "0"
fi

# SEC-02: string-interpolated/concatenated args passed to spawn/execFile (would
# reopen the shell-injection risk that args-array spawning is meant to close).
HITS=$(python3 -c "
import re, pathlib
for f in pathlib.Path('$SRC_DIR').rglob('*.ts'):
    text = f.read_text()
    for m in re.finditer(r'\b(spawn|execFile)\s*\(', text):
        start = m.start()
        depth, pos = 1, m.end()
        while pos < len(text) and depth > 0:
            if text[pos] == '(': depth += 1
            elif text[pos] == ')': depth -= 1
            pos += 1
        call_text = text[m.start():pos]
        if re.search(r'\`[^\`]*\\\$\{', call_text):
            line_num = text[:start].count(chr(10)) + 1
            print(f'{f}:{line_num}: template literal with interpolation in {m.group(1)}() args')
" 2>/dev/null || true)
COUNT=$(count_of "$HITS")
if [ "$COUNT" -gt 0 ]; then
    LOCS=$(echo "$HITS" | awk -F: '{print $1":"$2}')
    emit "SEC-02" "interpolated string in spawn/execFile args" "security" "warn" "$COUNT" $LOCS
else
    emit "SEC-02" "interpolated string in spawn/execFile args" "security" "pass" "0"
fi

# SEC-03: shell.openExternal call sites to verify against the https?:/mailto: allowlist
# regex (defense-in-depth that main/index.ts and main/ipc.ts both currently implement).
# Scans the call site plus the few lines before it for a guard (either the
# isSafeExternal() helper or an inline scheme regex test); only a call site with
# no guard evidence nearby gets flagged.
HITS=$(python3 -c "
import pathlib
for f in pathlib.Path('$SRC_DIR').rglob('*.ts'):
    lines = f.read_text().splitlines()
    for i, line in enumerate(lines):
        if 'shell.openExternal(' not in line:
            continue
        window = lines[max(0, i-4):i+1]
        guarded = any('isSafeExternal' in w or ('.test(' in w and 'https?' in w) for w in window)
        if not guarded:
            print(f'{f}:{i+1}: shell.openExternal() with no allowlist guard in the preceding lines')
" 2>/dev/null || true)
COUNT=$(count_of "$HITS")
if [ "$COUNT" -gt 0 ]; then
    LOCS=$(echo "$HITS" | awk -F: '{print $1":"$2}')
    emit "SEC-03" "shell.openExternal call site to verify against allowlist" "security" "warn" "$COUNT" $LOCS
else
    emit "SEC-03" "shell.openExternal call site to verify against allowlist" "security" "pass" "0"
fi

# SEC-04: hardcoded credential-shaped literals outside the documented skeleton
# constants (SKELETON_CONFIG in projects.ts is an intentional example template,
# and DEFAULT_GLOBALS in store.ts is the documented seeded default, not a leak).
HITS=$(python3 -c "
import re, pathlib
skip_files = {'projects.ts', 'store.ts'}
pattern = re.compile(r'(password|api_key|secret_key|token)\s*[:=]\s*[\"\\'][^\"\\']{3,}', re.IGNORECASE)
for f in pathlib.Path('$SRC_DIR').rglob('*.ts'):
    if f.name in skip_files:
        continue
    for i, line in enumerate(f.read_text().splitlines(), 1):
        if pattern.search(line) and 'isSecretColumn' not in line:
            print(f'{f}:{i}: hardcoded credential-shaped literal')
" 2>/dev/null || true)
COUNT=$(count_of "$HITS")
if [ "$COUNT" -gt 0 ]; then
    LOCS=$(echo "$HITS" | awk -F: '{print $1":"$2}')
    emit "SEC-04" "hardcoded credential-shaped literal" "security" "warn" "$COUNT" $LOCS
else
    emit "SEC-04" "hardcoded credential-shaped literal" "security" "pass" "0"
fi

# ============================================================
# GROUP REG: IPC Registration Completeness -> Reliability agent
# Cross-references the 4-file IPC contract CLAUDE.md documents:
# shared/ipc.ts (channel names) <-> main/ipc.ts (ipcMain.handle) <->
# preload/index.ts (contextBridge api) <-> shared/types.ts (TeutonApi)
# ============================================================

REG_RESULT=$(python3 -c "
import re, pathlib

root = pathlib.Path('$SRC_DIR')
ipc_file = root / 'shared' / 'ipc.ts'
main_ipc = root / 'main' / 'ipc.ts'
preload = root / 'preload' / 'index.ts'
types_file = root / 'shared' / 'types.ts'

if not (ipc_file.exists() and main_ipc.exists() and preload.exists() and types_file.exists()):
    print('SKIP')
    raise SystemExit

ipc_text = ipc_file.read_text()
channels = dict(re.findall(r'^\s*(\w+):\s*[\'\"]([\w:]+)[\'\"]', ipc_text, re.MULTILINE))

main_text = main_ipc.read_text()
handled = set(re.findall(r'ipcMain\.handle\(\s*IPC\.(\w+)', main_text))

# The preload/TeutonApi method name does NOT always match the shared/ipc.ts key
# name 1:1 -- this project has two deliberate exceptions (runStart -> run,
# runCancel -> cancelRun) for ergonomics. So we check preload wiring by looking
# for a literal IPC.<key> reference anywhere in preload/index.ts (regardless of
# which method name it's assigned to), not by key-name equality.
preload_text = preload.read_text()
referenced_in_preload = set(re.findall(r'IPC\.(\w+)', preload_text))

# preload's exposed api object keys and TeutonApi's method names DO have to
# match each other by name (that pairing has no naming exceptions in this
# project), so that comparison stays name-for-name.
exposed = set(re.findall(r'^\s*(\w+):\s*\(', preload_text, re.MULTILINE))

types_text = types_file.read_text()
api_match = re.search(r'interface TeutonApi \{(.*?)\n\}', types_text, re.DOTALL)
api_methods = set(re.findall(r'^\s*(\w+):', api_match.group(1), re.MULTILINE)) if api_match else set()

missing = []
for key in channels:
    if key == 'runEvent':
        continue  # push-only broadcast channel, not ipcMain.handle'd by design
    if key not in handled:
        missing.append(f'{main_ipc}:0: IPC.{key} defined in shared/ipc.ts but no ipcMain.handle(IPC.{key}...) found')
    if key not in referenced_in_preload:
        missing.append(f'{preload}:0: IPC.{key} is never referenced in preload/index.ts')

for method in exposed:
    if method not in api_methods:
        missing.append(f'{types_file}:0: preload exposes \"{method}\" but TeutonApi has no matching method')
for method in api_methods:
    if method not in exposed:
        missing.append(f'{preload}:0: TeutonApi declares \"{method}\" but preload never exposes it')

for m in missing:
    print(m)
if not missing:
    print('PASS')
")

if [ "$REG_RESULT" = "SKIP" ] || [ "$REG_RESULT" = "PASS" ]; then
    emit "REG-01" "IPC 4-file contract drift (ipc.ts/main/preload/types)" "architecture" "pass" "0"
else
    COUNT=$(count_of "$REG_RESULT")
    LOCS=$(echo "$REG_RESULT" | awk -F: '{print $1":"$2}')
    emit "REG-01" "IPC 4-file contract drift (ipc.ts/main/preload/types)" "architecture" "fail" "$COUNT" $LOCS
fi

# ============================================================
# GROUP EXC: Error-Handling / Data-Loss Checks -> Reliability agent
# ============================================================

# EXC-01: catch block that swallows a write failure (fs.writeFile immediately
# before the catch) with no re-throw and no user-facing surfaced error. Some of
# these are the documented "read-only project" convention (see store.ts) -- the
# agent must verify each one still matches that stated intent, not just its shape.
HITS=$(python3 -c "
import re, pathlib
for f in pathlib.Path('$SRC_DIR').rglob('*.ts'):
    lines = f.read_text().splitlines()
    for i, line in enumerate(lines):
        if re.search(r'await fs\.writeFile\(', line):
            for j in range(i+1, min(i+4, len(lines))):
                if re.match(r'\s*\}\s*catch', lines[j]):
                    # Scan the catch body (next few lines, up to its closing brace)
                    # for any real statement -- comments alone still count as
                    # swallowing, but a console.error/throw/etc. means it's logged.
                    body_lines = []
                    for k in range(j+1, min(j+6, len(lines))):
                        stripped = lines[k].strip()
                        if stripped == '}':
                            break
                        body_lines.append(stripped)
                    has_statement = any(
                        bl and not bl.startswith('//') for bl in body_lines
                    )
                    if not has_statement:
                        print(f'{f}:{i+1}: write immediately followed by a swallowing catch at line {j+1}')
                    break
" 2>/dev/null || true)
COUNT=$(count_of "$HITS")
if [ "$COUNT" -gt 0 ]; then
    LOCS=$(echo "$HITS" | awk -F: '{print $1":"$2}')
    emit "EXC-01" "write wrapped in a catch that swallows all errors" "architecture" "warn" "$COUNT" $LOCS
else
    emit "EXC-01" "write wrapped in a catch that swallows all errors" "architecture" "pass" "0"
fi

# EXC-02: setInterval in a file that never calls clearInterval anywhere in that same
# file (monitor.ts-style timer chains use setTimeout, not setInterval, and always
# pair a schedule with a clear -- the known-correct pattern in lib/run.ts).
HITS=$(python3 -c "
import pathlib
for f in pathlib.Path('$SRC_DIR').rglob('*.ts*'):
    text = f.read_text()
    if 'setInterval(' in text and 'clearInterval' not in text:
        line_num = text.split(chr(10)).index(next(l for l in text.split(chr(10)) if 'setInterval(' in l)) + 1
        print(f'{f}:{line_num}: setInterval() with no clearInterval anywhere in this file')
" 2>/dev/null || true)
COUNT=$(count_of "$HITS")
if [ "$COUNT" -gt 0 ]; then
    LOCS=$(echo "$HITS" | awk -F: '{print $1":"$2}')
    emit "EXC-02" "setInterval with no clearInterval in the same file" "architecture" "warn" "$COUNT" $LOCS
else
    emit "EXC-02" "setInterval with no clearInterval in the same file" "architecture" "pass" "0"
fi

# ============================================================
# GROUP DUP/DEAD/QUAL: Quality Checks -> Quality agent
# ============================================================

# DUP-01: the \p{L}\p{N} filename-sanitizer regex duplicated across main and
# renderer (they can't share a module across the Electron process boundary
# without a shared/ helper, but the two copies can silently drift apart).
HITS=$(grep -rnF '[^\p{L}\p{N} _.-]' --include='*.ts' --include='*.tsx' "$SRC_DIR" 2>/dev/null || true)
COUNT=$(count_of "$HITS")
if [ "$COUNT" -gt 1 ]; then
    LOCS=$(echo "$HITS" | awk -F: '{print $1":"$2}')
    emit "DUP-01" "filename-sanitizer regex duplicated across files" "quality" "warn" "$COUNT" $LOCS
else
    emit "DUP-01" "filename-sanitizer regex duplicated across files" "quality" "pass" "$COUNT"
fi

# DEAD-01: dependency declared in package.json but never imported anywhere in src/.
HITS=$(python3 -c "
import json, re, pathlib
pkg = json.loads(pathlib.Path('package.json').read_text())
deps = list(pkg.get('dependencies', {}).keys()) + list(pkg.get('devDependencies', {}).keys())
skip = {'electron', 'electron-builder', 'electron-vite', 'typescript', 'vite',
        '@vitejs/plugin-react', 'autoprefixer', 'postcss', 'tailwindcss',
        '@types/node', '@types/react', '@types/react-dom', '@types/js-yaml'}
src_text = ''
for f in pathlib.Path('$SRC_DIR').rglob('*.ts*'):
    src_text += f.read_text() + '\n'
for dep in deps:
    if dep in skip:
        continue
    if not re.search(re.escape(dep), src_text):
        print(f'package.json:0: dependency \"{dep}\" is never imported in $SRC_DIR')
" 2>/dev/null || true)
COUNT=$(count_of "$HITS")
if [ "$COUNT" -gt 0 ]; then
    LOCS=$(echo "$HITS" | awk -F: '{print $1":"$2}')
    emit "DEAD-01" "declared dependency never imported" "quality" "warn" "$COUNT" $LOCS
else
    emit "DEAD-01" "declared dependency never imported" "quality" "pass" "0"
fi

# QUAL-01: files over 400 lines (raised from the generic 300-line default: this
# stack's route files legitimately co-locate a view with its small private
# subcomponents, e.g. Dashboard.tsx's ListView/MatrixView/SortableTh).
HITS=$(find "$SRC_DIR" \( -name '*.ts' -o -name '*.tsx' \) 2>/dev/null \
    | xargs wc -l 2>/dev/null | awk '$1 > 400 && !/total$/ {print $2":"$1}' || true)
COUNT=$(count_of "$HITS")
if [ "$COUNT" -gt 0 ]; then
    LOCS=$(echo "$HITS" | awk -F: '{print $1}')
    emit "QUAL-01" "files over 400 lines" "quality" "info" "$COUNT" $LOCS
else
    emit "QUAL-01" "files over 400 lines" "quality" "pass" "0"
fi

# STYLE-01: eslint-disable comments with no eslint config present in the repo
# (a stale template artifact if there's genuinely no linter enforcing them).
if find . -maxdepth 1 \( -iname '.eslintrc*' -o -iname 'eslint.config.*' \) 2>/dev/null | grep -q .; then
    emit "STYLE-01" "eslint-disable comment but no eslint config in repo" "quality" "pass" "0"
else
    HITS=$(grep -rnF 'eslint-disable' --include='*.ts' --include='*.tsx' "$SRC_DIR" 2>/dev/null || true)
    COUNT=$(count_of "$HITS")
    if [ "$COUNT" -gt 0 ]; then
        LOCS=$(echo "$HITS" | awk -F: '{print $1":"$2}')
        emit "STYLE-01" "eslint-disable comment but no eslint config in repo" "quality" "info" "$COUNT" $LOCS
    else
        emit "STYLE-01" "eslint-disable comment but no eslint config in repo" "quality" "pass" "0"
    fi
fi

echo '' >> "$RESULTS_FILE"
echo '}' >> "$RESULTS_FILE"
cat "$RESULTS_FILE"
rm -f "$RESULTS_FILE"
